In [1]:
#Data collection
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
#Data preprocession to change categorial column-nominal value into one hot encoding
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
#input split
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [4]:
#output split
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
#model creation
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={ 'criterion' : ['squared_error','friedman_mse','absolute_error','poisson'] ,'max_features':['auto','sqrt','log2'], 'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
36 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.6339987  0.62252021 0.68006244 0.56619099
        nan        nan 0.66674045 0.57124171 0.67537547 0.58691354
        nan        nan 0.6324926  0.68989887 0.67746118 0.65811746
        nan        nan 0.70351949 0.62869734 0.66255484 0.64806843]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [9]:
res=grid.cv_results_
print("The R_Score value for best parameter{}".format(grid.best_params_))

The R_Score value for best parameter{'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'best'}

In [10]:
table=pd.DataFrame.from_dict(res)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001105,0.000031,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.001079,0.000041,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.005325,0.000962,0.002174,0.000034,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.756892,0.509639,0.727066,0.454545,0.721851,0.633999,0.125818,10
3,0.007953,0.005870,0.006429,0.008325,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.709774,0.483335,0.658298,0.605083,0.656111,0.622520,0.077069,13
4,0.008629,0.007278,0.003734,0.002642,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.676214,0.586451,0.727693,0.653598,0.756356,0.680062,0.059275,3
5,0.010875,0.009779,0.007703,0.007116,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.597619,0.557994,0.414878,0.617105,0.643358,0.566191,0.080620,16
6,0.000717,0.000053,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.000737,0.000114,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.011210,0.002717,0.003413,0.002227,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.681420,0.583516,0.713120,0.674545,0.681102,0.666740,0.043726,6
9,0.006830,0.003735,0.003010,0.001924,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.682705,0.563257,0.628722,0.484329,0.497196,0.571242,0.075932,15
10,0.008029,0.005033,0.002874,0.001884,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.724341,0.619003,0.687423,0.692746,0.653365,0.675375,0.036074,5
11,0.004249,0.000935,0.002992,0.000863,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.665742,0.496608,0.607517,0.585483,0.579219,0.586914,0.054506,14
12,0.000737,0.000073,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.000708,0.000048,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.025614,0.007831,0.002107,0.000079,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.688052,0.522323,0.557579,0.711434,0.683074,0.632493,0.076976,11
15,0.021292,0.008490,0.002182,0.000309,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.720243,0.591734,0.700160,0.754671,0.682687,0.689899,0.054607,2
16,0.022609,0.005199,0.003679,0.001892,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.755457,0.632159,0.650656,0.665876,0.683158,0.677461,0.042475,4
17,0.015969,0.002567,0.003681,0.003277,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.654295,0.604374,0.644604,0.737747,0.649567,0.658117,0.043588,8
18,0.000668,0.000053,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.000690,0.000092,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.006160,0.003145,0.003182,0.002386,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.737304,0.618149,0.734451,0.676448,0.751246,0.703519,0.049794,1
21,0.006228,0.003499,0.002946,0.001456,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.589942,0.557156,0.685795,0.681360,0.629234,0.628697,0.050307,12
22,0.005781,0.001209,0.001899,0.000110,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.731227,0.536914,0.674326,0.596523,0.773784,0.662555,0.086455,7
23,0.003297,0.000112,0.001827,0.000135,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.712823,0.546984,0.656986,0.667839,0.655711,0.648068,0.054663,9

In [12]:
age=float(input("Enter Age :"))
bmi=float(input("Enter BMI :"))
child=int(input("Enter number of children :"))
sex=int(input("Enter 1 for male and 0 for female :"))
smoker=int(input("Enter 1 for smoker and 0 for non-smoker :"))
Insurance_charges_predicted=grid.predict([[age,bmi,child,sex,smoker]])
print("Insurance_charges_predicted={}".format(Insurance_charges_predicted))

Enter Age : 32
Enter BMI : 43
Enter number of children : 2
Enter 1 for male and 0 for female : 0
Enter 1 for smoker and 0 for non-smoker : 1

Insurance_charges_predicted=[46113.511]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(