In [1]:
#Data collection
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
#Data preprocession to change categorial column-nominal value into one hot encoding
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
#input split
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [4]:
#output split
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
#model creation
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={ 'kernel' : ['rbf','linear'] ,'C':[10,100,1000,3000], 'gamma':['auto','scale']}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=1,n_jobs=2)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=2,
             param_grid={'C': [10, 100, 1000, 3000], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']},
             verbose=1)

In [9]:
res=grid.cv_results_
print("The R_Score value for best parameter{}".format(grid.best_params_))

The R_Score value for best parameter{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}

In [10]:
table=pd.DataFrame.from_dict(res)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.030203,0.000564,0.012743,0.000216,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.113791,-0.110741,-0.079156,-0.103389,-0.106488,-0.102713,0.012303,13
1,0.021371,0.001232,0.002860,0.000164,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,8
2,0.022587,0.001303,0.012525,0.000290,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,12
3,0.021347,0.001021,0.002744,0.000074,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,8
4,0.030716,0.001000,0.012325,0.000151,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.100012,-0.098456,-0.072981,-0.096615,-0.102232,-0.094059,0.010699,11
5,0.047926,0.003303,0.003786,0.000660,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,5
6,0.022502,0.001123,0.019669,0.014092,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,16
7,0.045071,0.001785,0.003057,0.000601,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,5
8,0.041797,0.003695,0.012376,0.000216,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.080692,-0.054347,-0.062876,-0.079329,-0.117983,-0.079045,0.021865,10
9,0.180431,0.021412,0.003882,0.000762,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
10,0.023468,0.000823,0.012150,0.000067,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.155430,-0.098267,-0.123724,-0.137137,-0.206405,-0.144193,0.036262,15
11,0.173142,0.017029,0.003467,0.000766,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
12,0.073781,0.004245,0.012303,0.000123,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.011741,0.043659,0.013383,0.021694,-0.012948,0.015506,0.018217,7
13,0.540173,0.109646,0.003885,0.000739,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,3
14,0.024786,0.000298,0.012130,0.000076,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.128958,-0.075578,-0.100199,-0.116051,-0.179304,-0.120018,0.034578,14
15,0.535479,0.117534,0.003558,0.000750,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,3

In [13]:
age=float(input("Enter Age :"))
bmi=float(input("Enter BMI :"))
child=int(input("Enter number of children :"))
sex=int(input("Enter 1 for male and 0 for female :"))
smoker=int(input("Enter 1 for smoker and 0 for non-smoker :"))
Insurance_charges_predicted=grid.predict([[age,bmi,child,sex,smoker]])
print("Insurance_charges_predicted={}".format(Insurance_charges_predicted))

Enter Age : 32
Enter BMI : 43
Enter number of children : 2
Enter 1 for male and 0 for female : 0
Enter 1 for smoker and 0 for non-smoker : 1

Insurance_charges_predicted=[30603.97396483]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(